from enum import IntEnum

# UUIDs for Polar device characteristics
HEART_RATE_CHAR_UUID: str = "00002a37-0000-1000-8000-00805f9b34fb"
PMD_CONTROL_POINT_UUID: str = "FB005C81-02E7-F387-1CAD-8ACD2D8DF0C8"
PMD_DATA_UUID: str = "FB005C82-02E7-F387-1CAD-8ACD2D8DF0C8"


class PmdMeasurementType(IntEnum):
    ECG = 0
    PPG = 1
    ACC = 2
    PPI = 3
    RFU = 4
    GYRO = 5
    MAG = 6


class PmdControlPointErrorCode(IntEnum):
    SUCCESS = 0
    ERROR_INVALID_OP_CODE = 1
    ERROR_INVALID_MEASUREMENT_TYPE = 2
    ERROR_NOT_SUPPORTED = 3
    ERROR_INVALID_LENGTH = 4
    ERROR_INVALID_PARAMETER = 5
    ERROR_ALREADY_IN_STATE = 6
    ERROR_INVALID_RESOLUTION = 7
    ERROR_INVALID_SAMPLE_RATE = 8
    ERROR_INVALID_RANGE = 9
    ERROR_INVALID_MTU = 10
    ERROR_INVALID_NUMBER_OF_CHANNELS = 11
    ERROR_INVALID_STATE = 12
    ERROR_DEVICE_IN_CHARGER = 13


# PMD Control Operation Codes
PMD_CONTROL_OPERATION_CODE: dict[str, int] = {"GET": 0x01, "START": 0x02, "STOP": 0x03}

# PMD Setting Types
PMD_SETTING_TYPES: list[str] = [
    "SAMPLE_RATE",
    "RESOLUTION",
    "RANGE",
    "RANGE_MILLIUNIT",
    "CHANNELS",
    "FACTOR",
    "SECURITY",
]

# PMD Setting Types to Field Sizes
PMD_SETTING_TYPES_TO_FIELD_SIZES: dict[str, int] = {
    "SAMPLE_RATE": 2,
    "RESOLUTION": 2,
    "RANGE": 2,
    "RANGE_MILLIUNIT": 4,
    "CHANNELS": 1,
    "FACTOR": 4,
    "SECURITY": 16,
}

# Timestamp Offset
TIMESTAMP_OFFSET: int = 946684800000000000
