# UUIDs for Polar device characteristics
HEART_RATE_CHAR_UUID: str = "00002a37-0000-1000-8000-00805f9b34fb"
PMD_CONTROL_POINT_UUID: str = "FB005C81-02E7-F387-1CAD-8ACD2D8DF0C8"
PMD_DATA_UUID: str = "FB005C82-02E7-F387-1CAD-8ACD2D8DF0C8"

# PMD Measurement Types
PMD_MEASUREMENT_TYPES: list[str] = ["ECG", "PPG", "ACC", "PPI", "RFU", "GYRO", "MAG"]

# PMD Control Point Error Codes
PMD_CONTROL_POINT_ERROR_CODES: list[str] = [
    "SUCCESS",
    "ERROR INVALID OP CODE",
    "ERROR INVALID MEASUREMENT TYPE",
    "ERROR NOT SUPPORTED",
    "ERROR INVALID LENGTH",
    "ERROR INVALID PARAMETER",
    "ERROR ALREADY IN STATE",
    "ERROR INVALID RESOLUTION",
    "ERROR INVALID SAMPLE RATE",
    "ERROR INVALID RANGE",
    "ERROR INVALID MTU",
    "ERROR INVALID NUMBER OF CHANNELS",
    "ERROR INVALID STATE",
    "ERROR DEVICE IN CHARGER",
]

# PMD Control Operation Codes
PMD_CONTROL_OPERATION_CODE: dict[str, int] = {"GET": 0x01, "START": 0x02, "STOP": 0x03}

# PMD Setting Types
PMD_SETTING_TYPES: list[str] = [
    "SAMPLE_RATE",
    "RESOLUTION",
    "RANGE",
    "RANGE_MILLIUNIT",
    "CHANNELS",
    "FACTOR",
    "SECURITY",
]

# PMD Setting Types to Field Sizes
PMD_SETTING_TYPES_TO_FIELD_SIZES: dict[str, int] = {
    "SAMPLE_RATE": 2,
    "RESOLUTION": 2,
    "RANGE": 2,
    "RANGE_MILLIUNIT": 4,
    "CHANNELS": 1,
    "FACTOR": 4,
    "SECURITY": 16,
}

# Timestamp Offset
TIMESTAMP_OFFSET: int = 946684800000000000
