from enum import IntEnum


class PmdControlPointErrorCode(IntEnum):
    SUCCESS = 0
    ERROR_INVALID_OP_CODE = 1
    ERROR_INVALID_MEASUREMENT_TYPE = 2
    ERROR_NOT_SUPPORTED = 3
    ERROR_INVALID_LENGTH = 4
    ERROR_INVALID_PARAMETER = 5
    ERROR_ALREADY_IN_STATE = 6
    ERROR_INVALID_RESOLUTION = 7
    ERROR_INVALID_SAMPLE_RATE = 8
    ERROR_INVALID_RANGE = 9
    ERROR_INVALID_MTU = 10
    ERROR_INVALID_NUMBER_OF_CHANNELS = 11
    ERROR_INVALID_STATE = 12
    ERROR_DEVICE_IN_CHARGER = 13
