name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        run: uv publish --token "${{ secrets.PYPI_API_TOKEN }}"
